### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [joselpadronc/OhMyPC#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by joselpadronc** [comment]
Hi, thanks for your comments. I just added the license. Thanks very much for add this little project to your repo.
